apiVersion: apps/v1
kind: Deployment
metadata:
  name: rad-dictionary-deployment
  labels:
    app: rad-dictionary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rad-dictionary
  template:
    metadata:
      labels:
        app: rad-dictionary
    spec:
      containers:
      - name: rad-dictionary
        image: 13111400/rad_dictionary:v2
        ports:
        - containerPort: 8080