apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  clusterIP: 10.107.31.184
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP