name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  publish_imaage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_USERNAME }}/rad_dictionary:latest
    - name: publish
      run: docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} && docker push ${{ vars.DOCKERHUB_USERNAME }}/rad_dictionary
